### ISSUE TITLE
Memory leak in rb_version_sort_1

### ISSUE THREAD

**Issue by philipturnbull** [github/version_sorter#16]
`rb_version_sort_1` manually allocates/frees `versions` which doesn't play nice with exceptions.

This is reasonably hard to hit but can be triggered by:

```
VersionSorter.sort(["1"]) { |x| raise 'oh noes' }
```

which causes an exception to be throw by `rb_yield`:
https://github.com/github/version_sorter/blob/fca9ae5c51bd01cab46650e45fb08bca10dd31e9/ext/version_sorter/version_sorter.c#L193-L194

and

```
VersionSorter.sort ["\0"]
```

which causes an exception to be thrown by `StringValueCStr` because it contains embedded NULs: https://github.com/github/version_sorter/blob/fca9ae5c51bd01cab46650e45fb08bca10dd31e9/ext/version_sorter/version_sorter.c#L198

**Comment by philipturnbull** [comment]
I just realised a similar problem occurs in `rb_version_compare` if the second `StringValueCStr` raises an exception because of embedded NULs:

https://github.com/github/version_sorter/blob/fca9ae5c51bd01cab46650e45fb08bca10dd31e9/ext/version_sorter/version_sorter.c#L238-L241

`version_a` is then leaked

**Comment by mislav** [comment]
Thank you for the detailed report! What would be a way to free up memory that is resilient to exceptions?

**Comment by kivikakk** [comment]
We should be able to use `rb_ensure`. I'll put a PR together.
