### ISSUE TITLE
Sorter changes encoding of sort items

### ISSUE THREAD

**Issue by Razer6** [github/version_sorter#3]
Given following example:
```ruby
require 'version_sorter'
versions = %w( 1.0 1.1-täst)

versions.each do |v|
  puts v.encoding
end

sorted = VersionSorter.rsort(versions)

sorted.each do |v|
  puts v.encoding
end
```

#### Expected
Input, as well as out has same encoding.

#### Observed
Input and output have different encoding. The encoding is changed from `UTF8` to `ASCII-8BIT`

```
UTF-8
UTF-8
ASCII-8BIT
ASCII-8BIT
```

**Comment by mislav** [comment]
[v1.1.1 now pushed](https://rubygems.org/gems/version_sorter/versions/1.1.1) to Rubygems; sorry about that!
