### ISSUE TITLE
bin/rake and bin/readygo

### ISSUE THREAD

**Issue by balasankarc** [github/version_sorter#8]
Hi,
I am packaging version_sorter for Debian and have some doubts
1. Is the file bin/rake same as the common rake (The one provided by the gem "rake" ). Or is there any difference?
2. What does the readygo file do? Is it a similar replacement to any existing program (like rake).

Hope you help me. Thanks.

**Comment by mislav** [comment]
1. Yes, `bin/rake` is a binstub for the `rake` command provided by gem "rake". It's only used in development and testing and doesn't need to be packaged.
2. `bin/readygo` runs the benchmark, which code loaded from `vendor/` directory. It's only used in development and doesn't need to be packaged.

Sorry for the late reply!
