### ISSUE TITLE
Allow sorting of arrays of arbitrary objects

### ISSUE THREAD

**Issue by eReGeBe** [github/version_sorter#9]
For example if I have a Tag class with an attribute `name`, and an array `tags` of objects of that class, currently I have to do something like this:

```rb
VersionSorter.sort(tags.map(&:name)).map do |tag_name|
  tags.find { |tag| tag.name == tag_name }
end
```

... which is rather inefficient.

Implementing some kind of "sort by" could be really helpful.

**Comment by mislav** [comment]
You could implement your own easily:

```rb
def sort_by(values, &block)
  values_map = {}
  values_to_sort = values.map do |val|
    transformed = block.call(val)
    values_map[transformed] = val
    transformed
  end
  VersionSorter.sort! values_to_sort
  values_to_sort.map { |val| values_map.fetch(v) }
end

# usage:
sorted_tags = sort_by(tags) { |t| t.name }
```

Hash lookup makes this a slightly more efficient implementation. But I agree, this feature being baked in could be useful for the library.
